# Generated by Django 3.2 on 2022-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220105_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production')], default='sales', max_length=10),
        ),
    ]
