# Generated by Django 3.2 on 2022-01-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220107_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
