# Generated by Django 3.2 on 2022-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220107_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user_type',
            name='user_type',
            field=models.CharField(choices=[('is_customer', 'is_customer'), ('is_manager', 'is_manager')], default='is_customer', max_length=20),
        ),
    ]
