# Generated by Django 3.2 on 2022-01-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220109_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_type',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
