# Generated by Django 3.2 on 2022-01-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220109_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='is_manager',
        ),
    ]
