# Generated by Django 3.2 on 2022-01-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220109_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customuser')),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customuser')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is Customer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is Manager'),
        ),
        migrations.DeleteModel(
            name='User_Type',
        ),
    ]
