# Generated by Django 3.2 on 2022-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220113_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production')], default='sales', help_text='For Managers only', max_length=10),
        ),
    ]
