# Generated by Django 3.2 on 2022-02-06 17:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dyrp3aqdq/image/upload/v1644094165/userimage_j61wqm.png', max_length=255, verbose_name='image'),
        ),
    ]
