# Generated by Django 3.2 on 2022-02-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220210_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
