# Generated by Django 3.2 on 2022-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
    ]
