# Generated by Django 3.2 on 2022-02-15 12:03

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('icon', models.CharField(choices=[('calendar', 'calendar'), ('clapperboard', 'clapperboard'), ('drive', 'drive')], default='calendar', max_length=20)),
                ('contract', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
