# Generated by Django 3.2 on 2022-01-25 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
